#DEFINE TMOVCON	0x90		; Configure Register for Timed Move Command
#DEFINE SMOVCON	0x91		; Configure Register for Sense Move Command
#DEFINE	TEMPR	0x92		; First placeholder register for calls (right side use)
#DEFINE TEMPL	0x93		; Second placeholder register for calls (left side use)
#DEFINE	DIST	0x94		; Storage for sense distance management
#DEFINE	SLOOK	0x95		; Safeguard to prevent sensor from getting caught in a loop
#DEFINE TCOUNT	0x96		; Stage counter for Timed move
#DEFINE SCOUNT	0x97		; Stage counter for Sense commands


